/**
 * Piezo Tune Player
 *
 * This sketch is a fan cover to the song 'Aozora no Rhapsody' by fhána from the anime 'Miss Kobayshi's Dragon Maid'.
 * Using a piezo buzzer the main melody for the song is played.
 *
 * @author Tony Pham
 */

/* Note sounds frequencies */
#define REST 0
#define NOTE_CS3 139
#define NOTE_DS3 156
#define NOTE_F3 175
#define NOTE_FS3 185
#define NOTE_G3 196
#define NOTE_GS3 208
#define NOTE_AS3 233
#define NOTE_C4 262
#define NOTE_CS4 277
#define NOTE_DS4 311
#define NOTE_E4 330
#define NOTE_F4 349
#define NOTE_FS4 370
#define NOTE_G4 392
#define NOTE_GS4 415
#define NOTE_A4 440
#define NOTE_AS4 466
#define NOTE_B4 494
#define NOTE_C5 523
#define NOTE_CS5 554
#define NOTE_D5 587
#define NOTE_DS5 622
#define NOTE_E5 659
#define NOTE_F5 698

 /* Note durations */
#define WHOLE 1.0
#define HALF 0.5
#define QUARTER 0.25
#define EIGHTH 0.125

/* Global Variables */
const int PIEZO_PIN = 15;
int tuneLength;

/* Tune Variables */
const int missKobayashiOpTune[] = {
  NOTE_C5, NOTE_D5, NOTE_C5,
  NOTE_C4, NOTE_A4, NOTE_F4, NOTE_G4, NOTE_A4, NOTE_C5,
  REST,
  NOTE_D5, NOTE_C5,
  NOTE_C4, NOTE_A4, NOTE_F4, NOTE_G4, NOTE_A4, NOTE_C5,
  REST,
  NOTE_D5, NOTE_D5, NOTE_C5,
  NOTE_C4, NOTE_A4, NOTE_F4, NOTE_G4, NOTE_A4, NOTE_C5,
  REST,
  NOTE_D5, NOTE_C5,
  NOTE_C4, NOTE_A4, NOTE_D5, NOTE_C5, NOTE_A4, NOTE_G4,
  NOTE_G3, NOTE_G3, NOTE_G3, NOTE_G3,
  NOTE_AS3, NOTE_AS3, NOTE_AS3, NOTE_AS3,
  NOTE_AS4, NOTE_AS4, NOTE_GS4, NOTE_G4, NOTE_GS4, NOTE_GS4, NOTE_AS4,
  NOTE_AS4, NOTE_C5, NOTE_CS5, NOTE_CS5, NOTE_C5, NOTE_CS5, NOTE_C5, NOTE_G4, NOTE_AS4,
  NOTE_AS4, NOTE_AS4, NOTE_GS4, NOTE_G4, NOTE_GS4, NOTE_AS4, NOTE_DS4,
  NOTE_DS4, NOTE_F4, NOTE_G4, NOTE_GS4, NOTE_G4, NOTE_GS4, NOTE_G4, NOTE_DS4, NOTE_DS4,
  NOTE_AS4, NOTE_AS4, NOTE_GS4, NOTE_G4, NOTE_GS4, NOTE_GS4, NOTE_AS4,
  NOTE_AS4, NOTE_C5, NOTE_CS5, NOTE_CS5, NOTE_C5, NOTE_CS5, NOTE_C5, NOTE_G4, NOTE_AS4,
  NOTE_AS4, NOTE_AS4, NOTE_GS4, NOTE_G4, NOTE_GS4, NOTE_AS4, NOTE_DS4,
  NOTE_DS4, NOTE_F4, NOTE_G4, NOTE_GS4, NOTE_G4, NOTE_GS4, NOTE_G4, NOTE_DS4, NOTE_DS4,
  NOTE_DS4, NOTE_F4, NOTE_G4, NOTE_GS4, NOTE_G4, NOTE_GS4, NOTE_AS4, NOTE_F4, NOTE_G4, NOTE_GS4,
  NOTE_AS4, NOTE_AS4, NOTE_AS4, NOTE_CS5, NOTE_C5, NOTE_AS4, NOTE_GS4, NOTE_C5, NOTE_DS4, NOTE_FS4,
  NOTE_GS4, NOTE_GS4, NOTE_GS4, NOTE_GS4, NOTE_AS4, NOTE_B4, NOTE_CS5, NOTE_AS4, NOTE_AS4, NOTE_FS4, NOTE_FS4, NOTE_CS4,
  NOTE_AS3, NOTE_AS3, NOTE_AS3, NOTE_AS3, NOTE_AS3, NOTE_AS3,
  NOTE_A4, NOTE_A4, NOTE_A4, NOTE_A4, NOTE_GS4, NOTE_FS4, NOTE_E4, NOTE_DS4, NOTE_E4, NOTE_GS4, NOTE_FS4, NOTE_GS4, NOTE_A4,
  NOTE_GS4, NOTE_FS4, NOTE_GS4, NOTE_GS4, NOTE_FS4, NOTE_GS4, NOTE_FS4, NOTE_GS4, NOTE_A4, NOTE_B4,
  NOTE_DS4, NOTE_FS4, NOTE_A4,
  NOTE_DS4, NOTE_FS4, NOTE_A4, NOTE_B4,
  NOTE_GS4, NOTE_B4, NOTE_CS5,
  NOTE_GS4, NOTE_FS4, NOTE_GS4, NOTE_FS4, NOTE_GS4, NOTE_FS4, NOTE_GS4, NOTE_CS5, NOTE_GS4, NOTE_FS4, NOTE_GS4, NOTE_CS5, NOTE_GS4, NOTE_FS4,
  NOTE_C4, NOTE_C4, NOTE_C4, NOTE_C4, NOTE_AS3,
  NOTE_DS3, NOTE_G3, NOTE_AS3, NOTE_CS4, NOTE_DS5, NOTE_AS4, NOTE_G4, NOTE_DS4,
  NOTE_DS4, NOTE_GS4, NOTE_DS5, NOTE_CS5, NOTE_C5, NOTE_GS4, NOTE_AS4, NOTE_AS4, NOTE_G4, NOTE_C5,
  NOTE_GS4, NOTE_AS4, NOTE_C5, NOTE_C5, NOTE_C5, NOTE_C5, NOTE_CS5, NOTE_DS5, NOTE_AS4,
  NOTE_GS3, NOTE_AS3, NOTE_GS3, NOTE_AS3, NOTE_GS3,
  NOTE_AS4, NOTE_GS4, NOTE_DS4, NOTE_DS4, NOTE_DS4, NOTE_DS4, NOTE_G4, NOTE_CS5, NOTE_AS4, NOTE_AS4, NOTE_GS4, NOTE_G4, NOTE_GS4,
  NOTE_GS4, NOTE_GS4, NOTE_AS4, NOTE_AS4, NOTE_AS4, NOTE_AS4, NOTE_C5, NOTE_CS5, NOTE_DS5,
  NOTE_DS4, NOTE_CS4, NOTE_CS4, NOTE_C4, NOTE_C4, NOTE_CS4, NOTE_C4, NOTE_AS3,
  NOTE_DS4, NOTE_DS4, NOTE_GS4, NOTE_DS5, NOTE_CS5, NOTE_C5, NOTE_GS4, NOTE_AS4, NOTE_AS4, NOTE_G4, NOTE_C5,
  NOTE_GS4, NOTE_AS4, NOTE_C5, NOTE_C5, NOTE_C5, NOTE_C5, NOTE_CS5, NOTE_DS5, NOTE_AS4,
  NOTE_GS3, NOTE_AS3, NOTE_GS3, NOTE_AS3, NOTE_GS3,
  NOTE_C5, NOTE_CS5, NOTE_DS5, NOTE_DS5, NOTE_DS5, NOTE_E5, NOTE_E5, NOTE_C5, NOTE_E5, NOTE_F5, NOTE_F5, NOTE_C5, NOTE_AS4, NOTE_GS4,
  NOTE_F4, NOTE_G4, NOTE_GS4, NOTE_AS4, NOTE_DS5, NOTE_DS5, NOTE_CS5, NOTE_C5, NOTE_CS5, NOTE_CS5, NOTE_C5, NOTE_AS4, NOTE_GS4,
  NOTE_GS4, NOTE_DS5, NOTE_DS5, NOTE_CS5, NOTE_C5, NOTE_CS5, NOTE_CS5, NOTE_DS5, NOTE_CS5, NOTE_C5,
  NOTE_GS4, NOTE_DS5, NOTE_DS5, NOTE_CS5, NOTE_C5, NOTE_CS5, NOTE_C5, NOTE_DS5, NOTE_G4, NOTE_GS4,
  NOTE_GS3, REST, NOTE_GS3, NOTE_FS4, NOTE_CS4, NOTE_DS4, NOTE_F4, NOTE_GS4, NOTE_F3, REST, NOTE_F3, NOTE_E4, NOTE_CS4, NOTE_C5, NOTE_CS5, NOTE_C5,
  NOTE_GS3, NOTE_FS3, NOTE_CS3, NOTE_DS3, NOTE_F3, NOTE_GS3,
  NOTE_DS4, NOTE_F4, NOTE_G4, NOTE_GS4, NOTE_CS5, NOTE_CS5, REST, NOTE_C5
};
const float missKobayashiOpDurations[] = {
  QUARTER, QUARTER, QUARTER,
  QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH,
  QUARTER,
  HALF, QUARTER,
  QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH,
  QUARTER,
  QUARTER, QUARTER, QUARTER,
  QUARTER, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH,
  QUARTER,
  HALF, QUARTER,
  QUARTER, HALF, EIGHTH, EIGHTH, EIGHTH, EIGHTH,
  QUARTER, QUARTER, QUARTER, HALF,
  QUARTER, QUARTER, QUARTER, HALF,
  QUARTER, EIGHTH, EIGHTH, EIGHTH, QUARTER, EIGHTH, HALF,
  EIGHTH, EIGHTH, QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, HALF,
  HALF, EIGHTH, EIGHTH, EIGHTH, QUARTER, EIGHTH, QUARTER,
  EIGHTH, EIGHTH, QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, EIGHTH, QUARTER,
  QUARTER, EIGHTH, EIGHTH, EIGHTH, QUARTER, EIGHTH, HALF,
  EIGHTH, EIGHTH, QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, HALF,
  HALF, EIGHTH, EIGHTH, EIGHTH, QUARTER, EIGHTH, QUARTER,
  EIGHTH, EIGHTH, QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, EIGHTH, QUARTER,
  EIGHTH, EIGHTH, QUARTER, EIGHTH, QUARTER, QUARTER, HALF, QUARTER, QUARTER, QUARTER,
  QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER, HALF,
  QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, EIGHTH, QUARTER, EIGHTH, HALF,
  EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH,
  QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, HALF, QUARTER, QUARTER, QUARTER,
  EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER,
  EIGHTH, EIGHTH, EIGHTH,
  EIGHTH, EIGHTH, EIGHTH, HALF,
  QUARTER, QUARTER, QUARTER,
  EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH,
  QUARTER, EIGHTH, QUARTER, EIGHTH, QUARTER,
  EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH,
  QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, WHOLE,
  EIGHTH, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, EIGHTH, WHOLE,
  QUARTER, QUARTER, QUARTER, QUARTER, QUARTER,
  EIGHTH, EIGHTH, QUARTER, QUARTER, EIGHTH, QUARTER, QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, HALF,
  EIGHTH, EIGHTH, QUARTER, QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER,
  EIGHTH, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH, EIGHTH, EIGHTH,
  EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, QUARTER, HALF,
  EIGHTH, EIGHTH, QUARTER, QUARTER, EIGHTH, QUARTER, QUARTER, EIGHTH, EIGHTH,
  EIGHTH, EIGHTH, EIGHTH, QUARTER, QUARTER,
  EIGHTH, EIGHTH, QUARTER, QUARTER, QUARTER, QUARTER, EIGHTH, QUARTER, QUARTER, QUARTER, EIGHTH, QUARTER, EIGHTH, EIGHTH,
  EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, QUARTER, EIGHTH, EIGHTH,
  EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, QUARTER,
  EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, QUARTER, QUARTER, QUARTER, EIGHTH, QUARTER,
  EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, QUARTER, QUARTER, EIGHTH, EIGHTH, EIGHTH, EIGHTH, QUARTER, QUARTER, HALF,
  QUARTER, EIGHTH, EIGHTH, EIGHTH, EIGHTH, WHOLE,
  EIGHTH, EIGHTH, EIGHTH, EIGHTH, EIGHTH, QUARTER, WHOLE, WHOLE
};

void setup() {
  pinMode(PIEZO_PIN, OUTPUT);
  tuneLength = sizeof(missKobayashiOpTune) / sizeof(missKobayashiOpTune[0]);
}

void loop() {
  for (int i = 0; i < tuneLength; i++) {
    tone(PIEZO_PIN, missKobayashiOpTune[i]);
    delay(1000 * missKobayashiOpDurations[i]);
    noTone(PIEZO_PIN);
  }
  delay(500);
}

/**
 * References
 * 1. 'Aozora no Rhapsody' played with Synthesia uploaded by 'MyReminiscence': https://www.youtube.com/watch?v=sG9tKEV510s
 * 2. 'Project 12 - Piezo Sounder Melody Player' from the 'Beginning Arduino' textbook written by Michael Roberts
 * 3. Physics of Music - Notes: https://pages.mtu.edu/~suits/notefreqs.html
 */
