#include "Note.h"
#include "Duration.h"

const int AI_NO_SUPREME_TUNE[] = {
    NOTE_D4, NOTE_E4, NOTE_FS4,
    NOTE_B3, NOTE_B3, NOTE_D4, NOTE_B3, NOTE_D4,
    NOTE_E4, NOTE_FS4, NOTE_G4,
    NOTE_FS4, NOTE_FS4, NOTE_E4, NOTE_D4, NOTE_E4,
    NOTE_FS4, NOTE_G4, NOTE_A4,
    NOTE_D4, NOTE_D4, NOTE_FS4, NOTE_D4, NOTE_FS4,
    NOTE_G4, NOTE_A4, NOTE_B4,
    NOTE_D5, NOTE_D5, NOTE_B4, NOTE_A4, NOTE_FS4,
    NOTE_FS5, NOTE_G5, NOTE_A5,
    NOTE_D5, NOTE_D5, NOTE_FS5, NOTE_D5, NOTE_FS5,
    NOTE_G5, NOTE_A5, NOTE_B5,
    NOTE_FS5, NOTE_FS5, NOTE_E5, NOTE_D5, NOTE_E5,
    NOTE_FS5, NOTE_G5, NOTE_A5,
    NOTE_D5, NOTE_D5, NOTE_FS5, NOTE_D5, NOTE_FS5,
    NOTE_G5, NOTE_A5, NOTE_B5,
    NOTE_D6, NOTE_D6, NOTE_B5, NOTE_A5, NOTE_FS5
};

const float AI_NO_SUPREME_DURATIONS[] = {
    QUARTER, QUARTER, HALF,
    QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER,
    QUARTER, QUARTER, HALF,
    QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER,
    QUARTER, QUARTER, HALF,
    QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER,
    QUARTER, QUARTER, HALF,
    QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER,
    QUARTER, QUARTER, HALF,
    QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER,
    QUARTER, QUARTER, HALF,
    QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER,
    QUARTER, QUARTER, HALF,
    QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER,
    QUARTER, QUARTER, HALF,
    QUARTER, EIGHTH, EIGHTH, QUARTER, QUARTER
};

// TIMESTAMP: 0:16
/**
 * References
 * 1. Kobayashi-san Chi no Maid Dragon S OP - "Ai no Supreme" | Piano Arrangement [Synthesia+Sheets] by Sakura Melodies: https://www.youtube.com/watch?v=dxH4w3Ptqps
 */